import { Injectable } from "@angular/core";
import { EventEmitter } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class AthletesService {
  athletes = [
    {
      id: "1",
      firstName: "Andrei",
      lastName: "Ionescu",
      test: "Long Jump",
      result1: "7.18",
      result2: "7.5",
      result3: "8.45",
    },
    {
      id: "2",
      firstName: "Mircea",
      lastName: "Barbu",
      test: "Running",
      result1: "293",
      result2: "253",
      result3: "231",
    },
    {
      id: "3",
      firstName: "Alexandru",
      lastName: "Mihailescu",
      test: "Pole Jump",
      result1: "4.8",
      result2: "5.14",
      result3: "5.7",
    },
    {
      id: "4",
      firstName: "Robert",
      lastName: "Paraschiv",
      test: "Shot Put",
      result1: "18.5",
      result2: "19.1",
      result3: "20.2",
    },
    {
      id: "5",
      firstName: "Mario",
      lastName: "Chiochina",
      test: "Running",
      result1: "270",
      result2: "255",
      result3: "280",
    },
    {
      id: "6",
      firstName: "Andreea",
      lastName: "Varlaam",
      test: "Swimming",
      result1: "30",
      result2: "28",
      result3: "23",
    },
    {
      id: "7",
      firstName: "Mihai ",
      lastName: "Popescu",
      test: "Pole Jump",
      result1: "3.75",
      result2: "4.1",
      result3: "4.8",
    },
    {
      id: "8",
      firstName: "Cristina",
      lastName: "Jora",
      test: "Long Jump",
      result1: "5.43",
      result2: "5.91",
      result3: "6.3",
    },
    {
      id: "9",
      firstName: "Elena",
      lastName: "Preotu",
      test: "Shot Put",
      result1: "15.33",
      result2: "15.5",
      result3: "16.8",
    },
    {
      id: "10",
      firstName: "Ionut",
      lastName: "Goga",
      test: "Swimming",
      result1: "40",
      result2: "37",
      result3: "39",
    },
    {
      id: "11",
      firstName: "Andrei",
      lastName: "Ionescu",
      test: "Running",
      result1: "261",
      result2: "273",
      result3: "288",
    },
    {
      id: "12",
      firstName: "Andrei",
      lastName: "Ionescu",
      test: "Pole Jump",
      result1: "4.3",
      result2: "4.9",
      result3: "5.7",
    },
    {
      id: "13",
      firstName: "Mircea",
      lastName: "Barbu",
      test: "Shot Put",
      result1: "16.3",
      result2: "17.1",
      result3: "18.6",
    },
    {
      id: "14",
      firstName: "Mircea",
      lastName: "Barbu",
      test: "Long Jump",
      result1: "6.4",
      result2: "7.1",
      result3: "7.5",
    },
    {
      id: "15",
      firstName: "Robert",
      lastName: "Paraschiv",
      test: "Swimming",
      result1: "35",
      result2: "39",
      result3: "42",
    },
    {
      id: "16",
      firstName: "Robert",
      lastName: "Paraschiv",
      test: "Pole Jump",
      result1: "4.8",
      result2: "5.3",
      result3: "5.5",
    },
    {
      id: "17",
      firstName: "Mario",
      lastName: "Chiochina",
      test: "Long Jump",
      result1: "5.5",
      result2: "6.4",
      result3: "7",
    },
    {
      id: "18",
      firstName: "Mario",
      lastName: "Chiochina",
      test: "Shot Put",
      result1: "15.53",
      result2: "16.21",
      result3: "16.9",
    },
    {
      id: "19",
      firstName: "Andreea",
      lastName: "Varlaam",
      test: "Running",
      result1: "300",
      result2: "293",
      result3: "289",
    },
    {
      id: "20",
      firstName: "Andreea",
      lastName: "Varlaam",
      test: "Long Jump",
      result1: "6.1",
      result2: "7",
      result3: "7.3",
    },
    {
      id: "21",
      firstName: "Cristina",
      lastName: "Jora",
      test: "Swimming",
      result1: "34",
      result2: "37",
      result3: "40",
    },
  ];
  eventSent = new EventEmitter<string>();
  constructor() {}
}
